### ISSUE TITLE
Setup Initial Integration Test Framework - Travis CI

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#185]
*Updating and defining this issue using the define METplus templates.* 

## Describe the Task ##
Setup an Initial automated testing and Continuous Integration Test Frame using DockerHub MET/METplus image and Travis CI.  The initial test frame work will be able to run a subset of the METplus pytests and integration tests (use_cases) and provide a framework that can change, grow, and be extended to meet the workflow and testing requirements of the METplus development lifecycle as it matures, while providing automated testing.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
The Estimate no longer applies since this task has been completed and is being
retrofitted to this issue template. However, **wall clock**, on this task took
months, there was a lot of learning of new tools, concepts and testing ...
In hind site it provides a good example showing the importance of breaking a task down in to manageable chunks ... But that is challenging to do when something is totally new and you don't really understand it enough to break it down
and one is really doing research, and synthesizing information and the problem.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [X] *None*

### Relevant Deadlines ###
End of AOP 2019

### Funding Source ###
*NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_185_initial_travis_ci`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by jimfrimel** [comment]
Connecting to issue #164 Clean up internal_test area

**Comment by jimfrimel** [comment]
Pushed the wrong button, closed ... Reopening ...

**Comment by jimfrimel** [comment]
METplus GItHub-DockerHub-Travis Picture overview.

![METplus_trifecta](https://user-images.githubusercontent.com/20955459/81939372-7900c680-95b3-11ea-9a21-8c983d4aaaa9.jpg)
![METplus_travisjob](https://user-images.githubusercontent.com/20955459/81941614-4ad0b600-95b6-11ea-87e0-7ec2436707a7.jpg)
